appId: "tech.inferis"
extraMetadata:
  main: 'dist/packages/desktop/main.js'
files:
  - 'package.json'
  - 'dist/packages/desktop/**'
  - '!dist/packages/desktop/dist/**'
linux:
  category: "Office"
  target:
    - target: "AppImage"
    - target: "deb"
    - target: "pacman"
mac:
  target: 'dmg'
  category: "public.app-category.medical"
win:
  target:
    - target: "nsis"
      arch: ['x64', 'ia32']
directories:
  output: 'dist/packages/desktop/dist'
publish:
  provider: 'github'
  releaseType: 'release'
nsis:
  differentialPackage: true
