name: Delete release assets

on:
  workflow_dispatch:

jobs:
  delete-release-assets:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get package version
        id: package
        run: echo "::set-output name=version::$(cat package.json | jq -r '.version')"

      - name: Delete release assets
        uses: ./.github/actions/delete-release-assets.yml
        with:
          tag: ${{ steps.package.version }}
          token: ${{ secrets.BOT_TOKEN }}
