name: General/global release

on:
   push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install package dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Get package version
        id: package_version
        run: |
          cat package.json | jq -r '.version'
          echo "::set-output name=tag::$(cat package.json | jq -r '.version')"

      - name: Publish release
        uses: ./.github/actions/publish-release
        with:
          tag: ${{ steps.package_version.outputs.tag }}
          token: ${{ secrets.BOT_TOKEN }}
