name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
    runs-on: self-hosted
    outputs:
       body: ${{ steps.release_drafter.outputs.body }}
       tag_name: ${{ steps.release_drafter.outputs.tag_name }}
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "dev"
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  set_version:
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    needs: update_release_draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Update npm version
        run: npm version --git-tag-version=false ${{ needs.update_release_draft.outputs.tag_name }}
      - name: Create pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update npm version
          body: |
            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.update_release_draft.

            ${{ needs.update_release_draft.outputs.body }}
          delete-branch: true
          title: Version bump ${{ needs.update_release_draft.outputs.tag_name }}}
          labels: skip-changelog,chore
