name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - dev
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: self-hosted
    outputs:
       tag_name: ${{ steps.release_drafter.outputs.tag_name }}
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "dev & master"
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  set_version:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && contains(github.event.pull_request.labels.*.name, 'release') }}
    runs-on: self-hosted
    needs: update_release_draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Update npm version
        run: npm version --git-tag-version=false ${{ needs.update_release_draft.outputs.tag_name }}
      - uses: EndBug/add-and-commit@v9
        with:
          message: Update version
          default_author: github_actions
  relase:
    needs: set_version
    uses: StaffOfHades/Workspace-Samples/.github/workflows/workflow-release.yml.yml@release
