name: Desktop release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies for differrent linux flavors
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install --no-install-recommends -y libopenjp2-tools libarchive-tools

      - name: Publish electron app
        run: |
          npm ci
          npx nx affected --target=package --projects=desktop --configuration=production
          ls -a dist/packages/desktop/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
