name: Desktop release

on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  release:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release') }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies for differrent linux flavors
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install --no-install-recommends -y libopenjp2-tools libarchive-tools

      - name: Publish electron app
        run: |
          npm ci
          npx nx affected --target=package --projects=desktop --configuration=production
          ls -a dist/packages/desktop/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add yaml files to server
        run: cp dist/packages/desktop/dist/*.yml packages/server/public/desktop-updates/

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: ${{ github.event.pull_request.head.ref }}
          branch: create-pull-request/release
          commit-message: Add desktop release files
          delete-branch: true
          title: Add desktop release files
          labels: skip-changelog,chore
